
const KEY='flexiBuddyDataV1';
const defaults=()=>({settings:{targetMinutes:480,paidBreakLimit:15,paidBreakCount:2,startingBalance:0,annualLeaveHours:0,defaultLocation:'Home',usualLunchMinutes:30,autoConvertPaidBreak:true,theme:'midnight',goalFlexiHours:0,goalMonthlyDays:0,remindBreak:false,remindFinish:false,remindStart:false,replaySpeed:18,dashboardOrder:['avgDay','avgStart','avgFinish','daysRecorded','reportBalance','leaveRemaining'],dashboardHidden:[],seenAchievements:[],workMode:'',travelStartedAt:null,favourites:['wfh','office','quick','travel','lunch','meeting'],diaryEdits:{}},events:[],days:[],reflections:[]});
function load(){let d;try{d=JSON.parse(localStorage.getItem(KEY))}catch(e){}d=d||defaults();d.settings={...defaults().settings,...(d.settings||{})};d.events=Array.isArray(d.events)?d.events:[];d.days=Array.isArray(d.days)?d.days:[];d.reflections=Array.isArray(d.reflections)?d.reflections:[];return d}
let data=load(),monthCursor=new Date(),selectedDay=null,creatingEntry=false;
const APP_VERSION='7.0.1';
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
const dayKey=x=>{let d=new Date(x);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const clock=x=>new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const fmt=m=>{m=Math.round(Number(m)||0);let s=m<0?'-':m>0?'+':'';m=Math.abs(m);let h=Math.floor(m/60),r=m%60;return h?`${s}${h}h ${pad(r)}m`:`${s}${r}m`};
const plain=m=>fmt(m).replace('+','');
const labels={work:'Started or resumed work',paid_break:'Paid break',lunch:'Lunch',pause:'Paused',location:'Changed location',credit:'Credit added',finish:'Finished work',unpaid_break:'Unpaid break',work_travel:'Work travel',quick_work:'Quick work',note:'Note'};
const icons={work:'▶',paid_break:'☕',lunch:'🍽',pause:'Ⅱ',location:'📍',credit:'＋',finish:'■',unpaid_break:'Ⅱ',work_travel:'🚗',quick_work:'⚡',note:'📝'};
function persist(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1600)}
function eventsFor(d){return data.events.filter(e=>dayKey(e.time)===d).sort((a,b)=>a.time-b.time)}
function currentState(){let e=eventsFor(dayKey(Date.now()));if(!e.length)return'idle';let t=e[e.length-1].type;return t==='finish'?'finished':t}
function latestLocation(d=dayKey(Date.now())){let e=eventsFor(d).filter(x=>x.location);return e.length?e[e.length-1].location:''}
function special(d){return data.days.find(x=>x.date===d)}
function hasFinished(d){return eventsFor(d).some(x=>x.type==='finish')}
function calc(d,live=true){let ev=eventsFor(d),work=0,paid=0,unpaid=0,paidSessions=0;for(let i=0;i<ev.length;i++){let e=ev[i],n=ev[i+1],end=n?n.time:(live&&d===dayKey(Date.now())&&e.type!=='finish'?Date.now():e.time),mins=Math.max(0,(end-e.time)/60000);if(['work','location','work_travel'].includes(e.type))work+=mins;if(e.type==='paid_break'){paidSessions++;let allowance=paidSessions<=Number(data.settings.paidBreakCount)?Number(data.settings.paidBreakLimit):0;paid+=Math.min(mins,allowance);unpaid+=Math.max(0,mins-allowance)}if(['pause','lunch','unpaid_break'].includes(e.type))unpaid+=mins}let credit=ev.filter(e=>['credit','quick_work'].includes(e.type)).reduce((s,e)=>s+Number(e.creditMinutes||0),0);return{work,paid,unpaid,credit}}
function daySplit(d,live=false){
  const ev=eventsFor(d), lunch=ev.find(e=>e.type==='lunch'), lunchTime=lunch?lunch.time:null;
  let before=0,after=0,paidBreak=0,lunchMinutes=0;
  for(let i=0;i<ev.length;i++){
    const e=ev[i],n=ev[i+1],end=n?n.time:(live&&d===dayKey(Date.now())&&e.type!=='finish'?Date.now():e.time);
    const mins=Math.max(0,(end-e.time)/60000);
    if(['work','location','work_travel'].includes(e.type)){
      if(lunchTime!==null && e.time>=lunchTime) after+=mins; else before+=mins;
    }
    if(e.type==='paid_break') paidBreak+=mins;
    if(e.type==='lunch') lunchMinutes+=mins;
  }
  ev.filter(e=>['credit','quick_work'].includes(e.type)).forEach(e=>{
    const mins=Number(e.creditMinutes||0);
    if(lunchTime!==null && e.time>=lunchTime) after+=mins; else before+=mins;
  });
  return{before,after,total:before+after,paidBreak,lunch:lunchMinutes};
}
function flexFor(d,live=false){let s=special(d);if(s){if(s.type==='flexi_day')return-Number(data.settings.targetMinutes);if(s.type==='part_flexi')return-(Number(s.hours||0)*60);return 0}let ev=eventsFor(d);if(!ev.length)return 0;if(!live&&d===dayKey(Date.now())&&!hasFinished(d))return 0;let c=calc(d,live);return Math.round(c.work+c.credit-Number(data.settings.targetMinutes))}
function allDates(){let set=new Set(data.events.map(e=>dayKey(e.time)));data.days.forEach(x=>set.add(x.date));return [...set].sort()}
function runningBalance(){return Number(data.settings.startingBalance||0)+allDates().reduce((s,d)=>s+(d===dayKey(Date.now())&&!hasFinished(d)&&!special(d)?0:flexFor(d,false)),0)}
function weekDates(ref=new Date()){let d=new Date(ref),mon=new Date(d);mon.setDate(d.getDate()-((d.getDay()+6)%7));return Array.from({length:7},(_,i)=>{let x=new Date(mon);x.setDate(mon.getDate()+i);return dayKey(x)})}
function addEvent(type,extra={}){data.events.push({id:'e'+Date.now()+Math.random().toString(16).slice(2),type,time:Date.now(),...extra});persist()}
function greeting(){let h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function finishPrediction(){let c=calc(dayKey(Date.now()),true),remaining=Math.max(0,Number(data.settings.targetMinutes)-c.work-c.credit);return new Date(Date.now()+remaining*60000)}
function averageEventMinutes(type,weekday=null){let arr=data.events.filter(e=>e.type===type&&(weekday===null||new Date(e.time).getDay()===weekday)).map(e=>{let d=new Date(e.time);return d.getHours()*60+d.getMinutes()});return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:null}
function workdayRecords(){return allDates().filter(d=>hasFinished(d)).map(d=>{let ev=eventsFor(d),start=ev.find(e=>e.type==='work'),finish=[...ev].reverse().find(e=>e.type==='finish'),c=calc(d,false);return{date:d,work:c.work,flex:flexFor(d,false),start:start?new Date(start.time).getHours()*60+new Date(start.time).getMinutes():null,finish:finish?new Date(finish.time).getHours()*60+new Date(finish.time).getMinutes():null,location:(ev.find(e=>e.location)||{}).location||'Unknown'}})}
function coachText(){let s=currentState(),d=dayKey(Date.now()),c=calc(d,true),remaining=Math.max(0,Number(data.settings.targetMinutes)-c.work-c.credit),week=weekDates().reduce((a,x)=>a+flexFor(x,false),0),weekday=new Date().getDay(),usualStart=averageEventMinutes('work',weekday),usualFinish=averageEventMinutes('finish',weekday),records=workdayRecords(),recent=records.slice(-5),recentAvg=recent.length?recent.reduce((a,r)=>a+r.work,0)/recent.length:0;
if(s==='idle'){if(usualStart!==null)return`On ${new Date().toLocaleDateString([],{weekday:'long'})}s you usually start around ${minsClock(usualStart)}. Starting now would put your target finish near ${clock(new Date(Date.now()+Number(data.settings.targetMinutes)*60000))}.`;return'Your day is ready. Start work and I will learn your usual rhythm, predict your finish and build your diary automatically.'}
if(s==='finished'){let today=flexFor(d,false),comparison=recentAvg?c.work-recentAvg:0;return`Day complete with ${fmt(today)} flexi. ${Math.abs(comparison)>15?`That was ${plain(Math.abs(comparison))} ${comparison>0?'longer':'shorter'} than your recent average.`:'That was close to your recent average.'}`}
if(s==='paid_break')return`You are on a paid break. Your first ${data.settings.paidBreakCount} break${data.settings.paidBreakCount==1?'':'s'} can count for up to ${data.settings.paidBreakLimit} minutes each; anything extra is separated automatically.`;
if(s==='lunch')return`You are on lunch. If you take your usual ${data.settings.usualLunchMinutes}-minute lunch from now, your estimated finish will be around ${clock(new Date(finishPrediction().getTime()+Number(data.settings.usualLunchMinutes)*60000))}.`;
if(s==='pause')return'Work is paused and no work time is being counted. Resume when you are ready and the finish estimate will immediately recalculate.';
if(remaining<=30)return`Nearly there — about ${Math.round(remaining)} minutes remain. Finishing at the prediction shown will land very close to your 8-hour target.`;
if(week>120)return`You have already built ${fmt(week)} this week. Today can be a steady target day rather than another long one.`;
if(usualFinish!==null){let predicted=finishPrediction(),diff=(predicted.getHours()*60+predicted.getMinutes())-usualFinish;return`Your predicted finish is ${Math.abs(diff)<15?'very close to':diff>0?'later than':'earlier than'} your usual ${new Date().toLocaleDateString([],{weekday:'long'})} finish of ${minsClock(usualFinish)}.`}
return`You have ${plain(remaining)} left to reach today’s target. The finish estimate will keep adjusting around breaks, lunch and pauses.`}
function briefingText(){let s=currentState(),loc=latestLocation()||data.settings.defaultLocation||'your usual location',date=new Date().toLocaleDateString([],{weekday:'long',day:'numeric',month:'long'});if(s==='idle')return`It is ${date}. You are set for ${loc}. Your current balance is ${fmt(runningBalance())}${data.settings.annualLeaveHours?`, with ${Math.max(0,Number(data.settings.annualLeaveHours)-annualLeaveUsed()).toFixed(1)} hours annual leave remaining`:''}.`;if(s==='finished')return`Your record for ${date} is complete. Reports and calendar have updated automatically.`;return`It is ${date}. You are currently working from ${loc}, and Flexi Buddy is keeping track in the background.`}
function actionHTML(){let s=currentState();if(s==='idle'||s==='finished')return`<button class="action primary" onclick="openStart()"><span class="ico">▶</span>${s==='finished'?'Start another session':'Start work'}</button>`;let resume=['paid_break','lunch','pause'].includes(s);return`${resume?`<button class="action primary" onclick="resumeWork()"><span class="ico">▶</span>Resume work</button>`:''}<button class="action" onclick="quickAction('paid_break')"><span class="ico">☕</span>Paid break</button><button class="action" onclick="quickAction('lunch')"><span class="ico">🍽</span>Lunch</button><button class="action" onclick="openPause()"><span class="ico">Ⅱ</span>Pause</button><button class="action" onclick="openLocation()"><span class="ico">📍</span>Location</button><button class="action primary danger" onclick="finishWork()"><span class="ico">■</span>Finish day</button>`}
function presetHTML(){let s=currentState(),active=!(s==='idle'||s==='finished');return`<button class="preset" onclick="quickLocation('Home')">🏠 WFH</button><button class="preset" onclick="quickLocation('Office')">🏢 Office</button><button class="preset" onclick="quickLocation('Home Visit')">🚗 Home visit</button><button class="preset" onclick="quickAction('meeting')">👥 Meeting</button><button class="preset" onclick="quickAction('work_travel')">🛣 Paid travel</button><button class="preset" onclick="quickAction('lunch')">🍽 Lunch</button>`}
function quickLocation(location){let s=currentState();if(s==='idle'||s==='finished'){addEvent('work',{location});toast(`Work started at ${location}`)}else{addEvent('location',{location});toast(`Now working at ${location}`)}}
function quickAction(type){let s=currentState();if(type==='meeting'){if(s==='idle'||s==='finished')addEvent('work',{location:data.settings.defaultLocation||'Home',note:'Meeting'});else addEvent('location',{location:latestLocation()||data.settings.defaultLocation||'Home',note:'Meeting'});toast('Meeting added to timeline');return}if(type==='work_travel'){if(s==='idle'||s==='finished')addEvent('work_travel',{location:'Work travel',note:'Paid travel'});else addEvent('work_travel',{location:latestLocation()||'Work travel',note:'Paid travel'});toast('Paid travel started');return}if((type==='lunch'||type==='paid_break')&&(s==='idle'||s==='finished')){toast('Start work first');return}addEvent(type);toast(type==='lunch'?'Lunch started':'Paid break started')}
let quickWorkKind='Email',quickWorkMinutes=5;
function openQuickWork(){quickWorkKind='Email';quickWorkMinutes=5;$('quickWorkNote').value='';document.querySelectorAll('#quickWorkTypes .quick-work-choice').forEach((b,i)=>b.classList.toggle('selected',i===0));document.querySelectorAll('#quickWorkDurations button').forEach(b=>b.classList.toggle('selected',b.dataset.minutes==='5'));$('quickWorkDialog').showModal()}
function selectQuickWorkType(btn){quickWorkKind=btn.dataset.kind;document.querySelectorAll('#quickWorkTypes .quick-work-choice').forEach(b=>b.classList.toggle('selected',b===btn))}
function selectQuickWorkDuration(btn){let v=btn.dataset.minutes;if(v==='custom'){let n=Number(prompt('How many minutes?','5'));if(!Number.isFinite(n)||n<=0)return;quickWorkMinutes=Math.min(240,Math.round(n));btn.textContent=quickWorkMinutes+'m'}else quickWorkMinutes=Number(v);document.querySelectorAll('#quickWorkDurations button').forEach(b=>b.classList.toggle('selected',b===btn))}
function saveQuickWork(){let note=$('quickWorkNote').value.trim(),kind=quickWorkKind;if(kind==='Other quick work'&&note)kind=note;data.events.push({id:'e'+Date.now()+Math.random().toString(16).slice(2),type:'quick_work',time:Date.now(),creditMinutes:quickWorkMinutes,note:kind+(note&&kind!==note?' · '+note:'')});closeDialog('quickWorkDialog');persist();toast(`${quickWorkMinutes} minutes of quick work added`)}
function quickWorkToday(){let ev=eventsFor(dayKey(Date.now())).filter(e=>e.type==='quick_work'),mins=ev.reduce((a,e)=>a+Number(e.creditMinutes||0),0);return{count:ev.length,mins}}
function renderToday(){let d=dayKey(Date.now()),c=calc(d,true),target=Number(data.settings.targetMinutes),pct=Math.min(100,Math.max(0,(c.work+c.credit)/target*100)),week=weekDates().reduce((a,x)=>a+flexFor(x,false),0),s=currentState(),loc=latestLocation()||data.settings.defaultLocation||'';$('greeting').textContent=greeting();$('briefing').textContent=briefingText();$('ring').style.setProperty('--p',pct);$('workedRing').textContent=plain(c.work);$('ring').querySelector('span').textContent=`of ${plain(target)}`;$('workedStat').textContent=plain(c.work);let split=daySplit(d,true);$('beforeLunchStat').textContent=plain(split.before);$('afterLunchStat').textContent=plain(split.after);$('appVersion').textContent='v'+APP_VERSION;$('todayFlex').textContent=fmt(flexFor(d,true));$('weekFlex').textContent=fmt(week);$('runningBalance').textContent=fmt(runningBalance());$('weekChip').textContent=`Week ${fmt(week)}`;$('balanceChip').textContent=`Balance ${fmt(runningBalance())}`;$('coach').textContent=coachText();$('locationPill').textContent=loc?`📍 ${loc}`:'📍 No location yet';$('stateBadge').textContent={idle:'Ready',finished:'Finished',work:'Working',location:'Working',work_travel:'Travelling',paid_break:'Paid break',lunch:'Lunch',pause:'Paused'}[s]||'Working';$('progressTitle').textContent=s==='finished'?'Day complete':s==='idle'?'Ready when you are':'On your way';$('prediction').innerHTML=(s==='idle'||s==='finished')?'Start work to see your finish prediction.':`Estimated finish<b>${clock(finishPrediction())}</b>`;$('actions').innerHTML=actionHTML();let ev=eventsFor(d);$('timeline').innerHTML=ev.length?ev.map(e=>`<div class="entry"><div class="entry-icon">${icons[e.type]||'•'}</div><div><b>${labels[e.type]||e.type}</b><small>${clock(e.time)}${e.location?' · '+escapeHTML(e.location):''}${e.note?' · '+escapeHTML(e.note):''}${['credit','quick_work'].includes(e.type)?' · '+Number(e.creditMinutes||0)+'m':''}</small></div><div class="entry-actions"><button onclick="editEntry('${e.id}')">Edit</button></div></div>`).join(''):'<div class="empty">Your day will appear here as soon as you start work.</div>';$('quickPresets').innerHTML=presetHTML()+`<button class="quick-work-btn" onclick="openQuickWork()">⚡ Quick work · email or messages</button>`;let qw=quickWorkToday();$('quickHint').innerHTML=qw.count?`<div class="quick-work-summary"><span>Quick work today · ${qw.count} ${qw.count===1?'entry':'entries'}</span><b>${plain(qw.mins)}</b></div>`:'One tap records the change and keeps your diary up to date.';renderWorkModeTools();renderFavourites();renderDiary();renderWeekSummary();renderReplay()}

let replayTimer=null,replayPosition=0;
function projectedWeekFlex(){let dates=weekDates(),today=dayKey(Date.now()),rec=workdayRecords().slice(-15),avg=rec.length?rec.reduce((a,r)=>a+r.flex,0)/rec.length:0,total=0;dates.forEach(d=>{let x=new Date(d+'T12:00'),sp=special(d);if(d<today||d===today&&hasFinished(d))total+=flexFor(d,false);else if(d===today&&currentState()!=='idle'&&currentState()!=='finished')total+=flexFor(d,true);else if(x.getDay()>0&&x.getDay()<6&&!sp)total+=avg});return Math.round(total)}
function renderWeekSummary(){let dates=weekDates().slice(0,5),worked=dates.reduce((a,d)=>a+calc(d,d===dayKey(Date.now())).work,0),target=Number(data.settings.targetMinutes)*5,pct=Math.min(100,worked/target*100),forecast=projectedWeekFlex();$('weekWorked').textContent=plain(worked);$('weekProgressBar').style.width=pct+'%';$('weekTargetText').textContent=`${plain(worked)} of ${plain(target)}`;$('weekForecastChip').textContent=`Forecast ${fmt(forecast)}`;$('weekForecastText').textContent=forecast>=0?'On track for target':'Below target forecast';$('weekDays').innerHTML=dates.map(d=>{let c=calc(d,d===dayKey(Date.now())),name=new Date(d+'T12:00').toLocaleDateString([],{weekday:'short'});return`<div class="week-day ${d===dayKey(Date.now())?'today':''}"><b>${name}</b><small>${c.work?plain(c.work):'—'}</small></div>`}).join('')}
function replayModel(){let ev=eventsFor(dayKey(Date.now()));if(ev.length<2)return null;let start=ev[0].time,end=(ev[ev.length-1].type==='finish'?ev[ev.length-1].time:Date.now());if(end<=start)return null;let segments=[];for(let i=0;i<ev.length;i++){let e=ev[i],next=ev[i+1],to=next?next.time:end;if(to<=e.time)continue;let cls=['work','location','work_travel'].includes(e.type)?'work':['paid_break','lunch'].includes(e.type)?'break':'pause';segments.push({left:(e.time-start)/(end-start)*100,width:(to-e.time)/(end-start)*100,cls,title:labels[e.type]||e.type})}return{ev,start,end,segments}}
function renderReplay(){let m=replayModel(),track=$('replayTrack');if(!m){track.innerHTML='';$('replayStatus').textContent='Record at least two actions to replay your day.';$('replayButton').disabled=true;return}$('replayButton').disabled=false;track.innerHTML=m.segments.map(x=>`<div class="replay-segment ${x.cls}" style="left:${x.left}%;width:${Math.max(.6,x.width)}%" title="${escapeHTML(x.title)}"></div>`).join('')+'<div class="replay-marker" id="replayMarker" style="left:'+replayPosition+'%"></div>';$('replayLabels').innerHTML=`<span>${clock(m.start)}</span><span>${clock(m.end)}</span>`;let t=m.start+(m.end-m.start)*replayPosition/100,prev=[...m.ev].reverse().find(e=>e.time<=t)||m.ev[0];$('replayStatus').textContent=`${clock(t)} · ${labels[prev.type]||prev.type}${prev.location?' · '+prev.location:''}`}
function toggleReplay(){if(replayTimer){clearInterval(replayTimer);replayTimer=null;$('replayButton').textContent='Resume replay';return}let m=replayModel();if(!m)return;if(replayPosition>=100)replayPosition=0;$('replayButton').textContent='Pause';replayTimer=setInterval(()=>{replayPosition+=1.25;if(replayPosition>=100){replayPosition=100;clearInterval(replayTimer);replayTimer=null;$('replayButton').textContent='Replay again'}renderReplay()},Number(data.settings.replaySpeed||18))}
function renderCalendar(){let y=monthCursor.getFullYear(),m=monthCursor.getMonth(),first=new Date(y,m,1),start=new Date(first);start.setDate(1-((first.getDay()+6)%7));$('monthTitle').textContent=first.toLocaleDateString([],{month:'long',year:'numeric'});let html=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<42;i++){let x=new Date(start);x.setDate(start.getDate()+i);let k=dayKey(x),sp=special(k),cls='day '+(x.getMonth()!==m?'out ':'')+(k===dayKey(Date.now())?'today ':'')+(sp?'leave ':eventsFor(k).length?'worked ':'');html+=`<button class="${cls}" onclick="showDay('${k}')">${x.getDate()}</button>`}$('calendarGrid').innerHTML=html}
function showDay(d){
  selectedDay=d;
  let sp=special(d),ev=eventsFor(d),c=calc(d,false),split=daySplit(d,false),title=new Date(d+'T12:00').toLocaleDateString([],{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  if(sp){
    $('dayDetail').className='';
    $('dayDetail').innerHTML=`<div class="section-head"><div><b>${title}</b><p>${sp.type.replaceAll('_',' ')}${sp.hours?' · '+sp.hours+' hours':''}</p></div><button class="softbtn" onclick="openNewEntry('${d}')">Add entry</button></div>`;
    return;
  }
  const summary=`<div class="day-timesheet"><div><span>Before lunch</span><b>${plain(split.before)}</b></div><div><span>After lunch & evening</span><b>${plain(split.after)}</b></div><div><span>Total paid work</span><b>${plain(split.total)}</b></div><div><span>Lunch</span><b>${plain(split.lunch)}</b></div><div><span>Flexi</span><b>${fmt(flexFor(d,false))}</b></div></div>`;
  const entries=ev.length?ev.map(e=>`<div class="entry"><div class="entry-icon">${icons[e.type]||'•'}</div><div><b>${labels[e.type]||e.type}</b><small>${clock(e.time)}${e.location?' · '+escapeHTML(e.location):''}${e.note?' · '+escapeHTML(e.note):''}${['credit','quick_work'].includes(e.type)?' · '+Number(e.creditMinutes||0)+'m':''}</small></div><div class="entry-actions"><button onclick="editEntry('${e.id}')">Edit</button></div></div>`).join(''):'<div class="empty">No entries yet. Add one below.</div>';
  $('dayDetail').className='';
  $('dayDetail').innerHTML=`<div class="section-head"><div><b>${title}</b><p>Worked ${plain(c.work+c.credit)} · Flexi ${fmt(flexFor(d,false))}</p></div><button class="btn" onclick="openNewEntry('${d}')">Add entry</button></div>${summary}<div class="timeline" style="margin-top:12px">${entries}</div>`;
}
function openNewEntry(d=selectedDay){
  creatingEntry=true; selectedDay=d;
  $('editId').value=''; $('editType').value='work';
  const local=new Date(d+'T09:00:00');
  $('editTime').value=new Date(local.getTime()-local.getTimezoneOffset()*60000).toISOString().slice(0,16);
  $('editLocation').value=data.settings.defaultLocation||'Home'; $('editNote').value=''; $('editCredit').value='';
  document.querySelector('#editDialog h2').textContent='Add entry'; $('deleteEntryButton').style.display='none'; $('saveEntryButton').textContent='Add entry';
  $('editDialog').showModal();
}
let currentChart='hours';
function minsClock(v){if(v===null||!isFinite(v))return'—';v=Math.round(v);return`${pad(Math.floor(v/60)%24)}:${pad(v%60)}`}
function annualLeaveUsed(){return data.days.filter(x=>x.type==='annual_leave').reduce((s,x)=>s+(Number(x.hours)||Number(data.settings.targetMinutes)/60),0)}
function setChart(type,btn){currentChart=type;document.querySelectorAll('.chart-tab').forEach(x=>x.classList.toggle('active',x===btn));renderAdvancedChart()}
function chartSeries(){let rec=workdayRecords().slice(-14);if(currentChart==='hours')return{records:rec,values:rec.map(r=>r.work/60),label:v=>`${v.toFixed(1)}h`};if(currentChart==='flexi'){let balance=Number(data.settings.startingBalance||0),all=allDates();let map=new Map();all.forEach(d=>{balance+=flexFor(d,false);map.set(d,balance/60)});rec=all.slice(-14).map(d=>({date:d}));return{records:rec,values:rec.map(r=>map.get(r.date)||0),label:v=>`${v>=0?'+':''}${v.toFixed(1)}h`}};if(currentChart==='start')return{records:rec.filter(r=>r.start!==null),values:rec.filter(r=>r.start!==null).map(r=>r.start),label:minsClock};return{records:rec.filter(r=>r.finish!==null),values:rec.filter(r=>r.finish!==null).map(r=>r.finish),label:minsClock}}
function renderAdvancedChart(){let box=$('advancedChart'),s=chartSeries();if(!s.records.length){box.innerHTML='<div class="empty" style="margin-top:12px">Complete a few workdays to see this trend.</div>';return}let vals=s.values,min=Math.min(...vals),max=Math.max(...vals);if(max===min){max+=1;min-=1}let w=700,h=210,padX=34,padY=25,points=vals.map((v,i)=>{let x=padX+(s.records.length===1?0:(i/(s.records.length-1))*(w-padX*2)),y=padY+(1-(v-min)/(max-min))*(h-padY*2);return{x,y,v,date:s.records[i].date}});let path=points.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '),grid=[0,.5,1].map(t=>{let y=padY+t*(h-padY*2),v=max-t*(max-min);return`<line class="gridline" x1="${padX}" y1="${y}" x2="${w-padX}" y2="${y}"/><text x="2" y="${y+3}">${s.label(v)}</text>`}).join(''),dots=points.map(p=>`<circle class="dot" cx="${p.x}" cy="${p.y}" r="5"><title>${p.date}: ${s.label(p.v)}</title></circle>`).join(''),labels=points.filter((_,i)=>i===0||i===points.length-1||i===Math.floor(points.length/2)).map(p=>`<text text-anchor="middle" x="${p.x}" y="${h-2}">${new Date(p.date+'T12:00').toLocaleDateString([],{day:'numeric',month:'short'})}</text>`).join('');box.innerHTML=`<svg class="line-chart" viewBox="0 0 ${w} ${h}" role="img">${grid}<path class="trend" d="${path}"/>${dots}${labels}</svg>`}
function renderHeatmap(){let end=new Date(),start=new Date();start.setDate(end.getDate()-97);let html='';for(let i=0;i<98;i++){let d=new Date(start);d.setDate(start.getDate()+i);let key=dayKey(d),mins=calc(key,false).work,level=mins?Math.min(4,Math.max(1,Math.ceil(mins/120))):0;html+=`<div class="heat ${level?'l'+level:''}" title="${key}: ${mins?plain(mins):'No work recorded'}"></div>`}$('heatmap').innerHTML=html}
function locationStats(){let counts={};workdayRecords().forEach(r=>counts[r.location]=(counts[r.location]||0)+1);return Object.entries(counts).sort((a,b)=>b[1]-a[1])}
function renderLocations(){let stats=locationStats(),max=Math.max(1,...stats.map(x=>x[1]));$('locationBars').innerHTML=stats.length?stats.map(([name,count])=>`<div class="location-row"><span>${escapeHTML(name)}</span><div class="location-track"><span style="width:${count/max*100}%"></span></div><b>${count}</b></div>`).join(''):'<div class="empty">Locations will appear after completed workdays.</div>'}
function smartInsights(){let rec=workdayRecords(),out=[];if(!rec.length)return[{icon:'✦',title:'Ready to learn',text:'Complete a few workdays and Flexi Buddy will begin spotting your patterns.'}];let avg=rec.reduce((a,r)=>a+r.work,0)/rec.length,longest=Math.max(...rec.map(r=>r.work)),best=Math.max(...rec.map(r=>r.flex)),weekday=new Date().getDay(),dayRec=rec.filter(r=>new Date(r.date+'T12:00').getDay()===weekday),dayFinish=dayRec.filter(r=>r.finish!==null);out.push({icon:'◷',title:'Your typical day',text:`Your average completed day is ${plain(avg)}.`});if(dayFinish.length)out.push({icon:'↗',title:`Usual ${new Date().toLocaleDateString([],{weekday:'long'})} finish`,text:`You normally finish around ${minsClock(dayFinish.reduce((a,r)=>a+r.finish,0)/dayFinish.length)}.`});out.push({icon:'★',title:'Longest recorded day',text:`Your longest completed workday is ${plain(longest)}.`});out.push({icon:'＋',title:'Best flexi day',text:`Your strongest single-day gain is ${fmt(best)}.`});return out.slice(0,4)}
function renderInsights(){$('insightList').innerHTML=smartInsights().map(x=>`<div class="insight"><div class="insight-icon">${x.icon}</div><div><b>${x.title}</b><p>${x.text}</p></div></div>`).join('')}
function streakCount(){let dates=workdayRecords().map(r=>r.date).sort().reverse();if(!dates.length)return 0;let count=0,cursor=new Date();for(let safety=0;safety<60;safety++){let key=dayKey(cursor),weekday=cursor.getDay();if(weekday!==0&&weekday!==6){if(dates.includes(key))count++;else if(key!==dayKey(Date.now()))break}cursor.setDate(cursor.getDate()-1)}return count}
function milestoneData(){let rec=workdayRecords(),total=rec.reduce((a,r)=>a+r.work,0),balance=runningBalance(),streak=streakCount(),locations=locationStats().length;return[
{icon:'🌱',title:'First day',text:'Complete your first tracked workday.',value:rec.length,target:1},
{icon:'📅',title:'Ten workdays',text:'Build a reliable ten-day record.',value:rec.length,target:10},
{icon:'💯',title:'One hundred hours',text:'Record 100 completed working hours.',value:total/60,target:100},
{icon:'🔥',title:'Five-day streak',text:'Record five consecutive working days.',value:streak,target:5},
{icon:'✨',title:'Ten hours flexi',text:'Reach a running balance of +10 hours.',value:Math.max(0,balance/60),target:10},
{icon:'📍',title:'Flexible worker',text:'Record work in three different locations.',value:locations,target:3}
]}
function renderMilestones(){let items=milestoneData(),unlocked=items.filter(x=>x.value>=x.target).length;$('unlockedCount').textContent=`${unlocked} unlocked`;$('milestones').innerHTML=items.map(x=>{let p=Math.min(100,x.value/x.target*100),done=x.value>=x.target;return`<div class="milestone ${done?'':'locked'}"><div class="badge-icon">${x.icon}</div><b>${x.title}${done?' ✓':''}</b><p>${x.text}</p><div class="progress-small"><span style="width:${p}%"></span></div></div>`}).join('')}

const widgetNames={avgDay:'Average working day',avgStart:'Average start',avgFinish:'Average finish',daysRecorded:'Days recorded',reportBalance:'Current balance',leaveRemaining:'Leave remaining'};
function dashboardOrder(){let base=Object.keys(widgetNames),saved=Array.isArray(data.settings.dashboardOrder)?data.settings.dashboardOrder:[];return [...saved.filter(x=>base.includes(x)),...base.filter(x=>!saved.includes(x))]}
function applyDashboardLayout(){let grid=$('dashboardGrid');if(!grid)return;dashboardOrder().forEach(id=>{let tile=grid.querySelector(`[data-widget="${id}"]`);if(tile){tile.hidden=(data.settings.dashboardHidden||[]).includes(id);grid.appendChild(tile)}});renderWidgetOptions();bindDashboardDrag()}
function renderWidgetOptions(){let box=$('widgetOptions');if(!box)return;let hidden=data.settings.dashboardHidden||[];box.innerHTML=dashboardOrder().map((id,i)=>`<div class="widget-option"><div><b>${widgetNames[id]}</b><small style="display:block;color:var(--muted)">Position ${i+1}</small></div><label class="switch"><input type="checkbox" ${hidden.includes(id)?'':'checked'} onchange="toggleWidget('${id}',this.checked)"><span class="slider"></span></label></div>`).join('')}
function toggleWidget(id,show){let h=new Set(data.settings.dashboardHidden||[]);show?h.delete(id):h.add(id);data.settings.dashboardHidden=[...h];persist()}
function toggleDashboardCustomise(){$('customisePanel').classList.toggle('open')}
function resetDashboardLayout(){data.settings.dashboardOrder=Object.keys(widgetNames);data.settings.dashboardHidden=[];persist();toast('Dashboard reset')}
function bindDashboardDrag(){let grid=$('dashboardGrid');if(!grid||grid.dataset.bound)return;grid.dataset.bound='1';let dragged=null;grid.addEventListener('dragstart',e=>{let t=e.target.closest('.dashboard-tile');if(!t)return;dragged=t;t.classList.add('dragging')});grid.addEventListener('dragend',()=>{if(dragged)dragged.classList.remove('dragging');dragged=null;data.settings.dashboardOrder=[...grid.querySelectorAll('.dashboard-tile')].map(x=>x.dataset.widget);localStorage.setItem(KEY,JSON.stringify(data));renderWidgetOptions()});grid.addEventListener('dragover',e=>{e.preventDefault();let target=e.target.closest('.dashboard-tile');if(!dragged||!target||target===dragged)return;let r=target.getBoundingClientRect();grid.insertBefore(dragged,(e.clientY-r.top)>r.height/2?target.nextSibling:target)})}
function monthRecords(){let now=new Date(),ym=`${now.getFullYear()}-${pad(now.getMonth()+1)}`;return workdayRecords().filter(r=>r.date.startsWith(ym))}
function renderMonthlyReview(){let rec=monthRecords(),worked=rec.reduce((a,r)=>a+r.work,0),flex=rec.reduce((a,r)=>a+r.flex,0),target=Number(data.settings.targetMinutes||480),good=rec.filter(r=>r.work>=target).length,loc={};rec.forEach(r=>eventsFor(r.date).filter(e=>e.location).forEach(e=>loc[e.location]=(loc[e.location]||0)+1));let top=Object.entries(loc).sort((a,b)=>b[1]-a[1])[0]?.[0]||'No location yet',month=new Date().toLocaleDateString([],{month:'long',year:'numeric'});$('reviewTitle').textContent=`${month} review`;$('monthlyReviewGrid').innerHTML=[['Hours worked',plain(worked)],['Flexi change',fmt(flex)],['Days recorded',rec.length],['Target days',good]].map(x=>`<div class="review-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');$('monthlyReviewSummary').textContent=rec.length?`You recorded ${rec.length} workday${rec.length===1?'':'s'} this month. Your most-used location was ${top}. ${flex>=0?'You are building flexi overall.':'Your month is currently below target, so the Coach forecast may help you plan the remaining days.'}`:'Complete your first workday this month to generate a monthly review.'}
function printMonthlyReview(){window.print()}
function checkAchievements(){let unlocked=milestoneData().filter(x=>x.value>=x.target),seen=new Set(data.settings.seenAchievements||[]),fresh=unlocked.find(x=>!seen.has(x.title));if(!fresh)return;seen.add(fresh.title);data.settings.seenAchievements=[...seen];localStorage.setItem(KEY,JSON.stringify(data));$('achievementTitle').textContent=`${fresh.icon} ${fresh.title}`;$('achievementText').textContent=fresh.text;let pop=$('achievementPop');pop.classList.add('show');setTimeout(()=>pop.classList.remove('show'),4200)}
function renderGoalProgress(){let flexGoal=Number(data.settings.goalFlexiHours||0)*60,dayGoal=Number(data.settings.goalMonthlyDays||0),balance=Math.max(0,runningBalance()),days=monthRecords().length;if($('goalFlexiBar'))$('goalFlexiBar').style.width=(flexGoal?Math.min(100,balance/flexGoal*100):0)+'%';if($('goalDaysBar'))$('goalDaysBar').style.width=(dayGoal?Math.min(100,days/dayGoal*100):0)+'%'}
function renderReports(){let rec=workdayRecords(),avg=rec.length?rec.reduce((a,r)=>a+r.work,0)/rec.length:0,starts=rec.filter(r=>r.start!==null),finishes=rec.filter(r=>r.finish!==null),avgS=starts.length?starts.reduce((a,r)=>a+r.start,0)/starts.length:null,avgF=finishes.length?finishes.reduce((a,r)=>a+r.finish,0)/finishes.length:null,remaining=Math.max(0,Number(data.settings.annualLeaveHours||0)-annualLeaveUsed());$('avgDay').textContent=avg?plain(avg):'—';$('avgStart').textContent=minsClock(avgS);$('avgFinish').textContent=minsClock(avgF);$('daysRecorded').textContent=rec.length;$('reportBalance').textContent=fmt(runningBalance());$('leaveRemaining').textContent=data.settings.annualLeaveHours?`${remaining.toFixed(1)}h`:'Not set';$('recordedPeriod').textContent=rec.length?`Since ${new Date(rec[0].date+'T12:00').toLocaleDateString([],{month:'short',year:'numeric'})}`:'All time';renderAdvancedChart();renderHeatmap();renderLocations();renderInsights();renderMilestones();applyDashboardLayout();renderMonthlyReview();checkAchievements()}
function renderLeave(){let list=[...data.days].sort((a,b)=>b.date.localeCompare(a.date));$('leaveList').innerHTML=list.length?list.map((x,i)=>`<div class="list-item"><div><b>${new Date(x.date+'T12:00').toLocaleDateString([],{day:'numeric',month:'short',year:'numeric'})}</b><small style="display:block;color:var(--muted)">${x.type.replaceAll('_',' ')}${x.hours?' · '+x.hours+'h':''}</small></div><button class="softbtn" onclick="deleteLeave(${i})">Delete</button></div>`).join(''):'<div class="empty">No leave has been recorded yet.</div>'}
function renderSettings(){$('targetHours').value=Number(data.settings.targetMinutes)/60;$('startingBalance').value=data.settings.startingBalance||0;$('paidBreakLimit').value=data.settings.paidBreakLimit||0;$('paidBreakCount').value=data.settings.paidBreakCount||0;$('lunchMinutes').value=data.settings.usualLunchMinutes||30;$('defaultLocation').value=data.settings.defaultLocation||'Home';$('annualLeave').value=data.settings.annualLeaveHours||0}
function setTheme(theme){data.settings.theme=theme;document.body.dataset.theme=theme;document.querySelectorAll('.theme-btn').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme));localStorage.setItem(KEY,JSON.stringify(data));toast(`${theme[0].toUpperCase()+theme.slice(1)} theme applied`)}
function renderTheme(){let theme=data.settings.theme||'midnight';document.body.dataset.theme=theme;document.querySelectorAll('.theme-btn').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme))}

let searchFilter='all',plannerYear=new Date().getFullYear();
function coachScore(){let rec=workdayRecords(),score=55;if(rec.length>=5)score+=10;if(rec.length>=15)score+=10;let week=weekDates().reduce((a,x)=>a+flexFor(x,false),0);if(Math.abs(week)<=120)score+=10;let s=currentState();if(['work','location','work_travel'].includes(s))score+=8;if(s==='finished')score+=12;return Math.min(100,score)}
function forecastBalance(days){let rec=workdayRecords().slice(-10),avg=rec.length?rec.reduce((a,r)=>a+r.flex,0)/rec.length:0,weekdays=0,d=new Date();for(let i=1;i<=days;i++){let x=new Date(d);x.setDate(d.getDate()+i);if(x.getDay()>0&&x.getDay()<6)weekdays++}return runningBalance()+avg*weekdays}
function coachAdviceItems(){let out=[],s=currentState(),d=dayKey(Date.now()),c=calc(d,true),remaining=Math.max(0,data.settings.targetMinutes-c.work-c.credit),week=weekDates().reduce((a,x)=>a+flexFor(x,false),0);if(s==='idle')out.push({i:'▶',t:'Start when ready',p:`Your target day is ${plain(data.settings.targetMinutes)}. I will recalculate your finish as the day changes.`});if(['work','location','work_travel'].includes(s)){out.push({i:'⏱',t:'Current finish prediction',p:`Staying on task puts your estimated finish at ${clock(finishPrediction())}.`});if(remaining<60)out.push({i:'✓',t:'You are close',p:`Around ${plain(remaining)} remains to reach today’s target.`})}if(week>120)out.push({i:'⚖',t:'Protect your energy',p:`You have already built ${fmt(week)} this week, so a target-length day may be enough.`});if(data.settings.annualLeaveHours&&annualLeaveUsed()/data.settings.annualLeaveHours>.75)out.push({i:'🌴',t:'Leave is running low',p:'More than three quarters of your annual leave allowance is already recorded.'});if(!workdayRecords().length)out.push({i:'🌱',t:'Learning mode',p:'Complete a few days and the coach will begin comparing weekday patterns and forecasting future balances.'});return out.slice(0,4)}
function renderCoach(){let score=coachScore(),rec=workdayRecords(),avg=rec.length?rec.reduce((a,r)=>a+r.work,0)/rec.length:0;$('coachScore').innerHTML=`${score}<small>/100</small>`;$('coachHeadline').textContent=score>85?'Strong, balanced pattern':score>70?'Your pattern is taking shape':'Building your working rhythm';$('coachSummary').textContent=coachText();$('forecastRows').innerHTML=[['Current balance',fmt(runningBalance())],['End of this week',fmt(forecastBalance(7))],['In four weeks',fmt(forecastBalance(28))]].map(x=>`<div class="forecast-row"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('coachAdvice').innerHTML=coachAdviceItems().map(x=>`<div class="advice"><div class="advice-ico">${x.i}</div><div><b>${x.t}</b><p>${x.p}</p></div></div>`).join('');let starts=rec.filter(r=>r.start!==null),fin=rec.filter(r=>r.finish!==null);$('habitGrid').innerHTML=[['Average day',avg?plain(avg):'—'],['Usual start',minsClock(starts.length?starts.reduce((a,r)=>a+r.start,0)/starts.length:null)],['Usual finish',minsClock(fin.length?fin.reduce((a,r)=>a+r.finish,0)/fin.length:null)],['Current streak',streakCount()+' days']].map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');let pred=finishPrediction();$('whatIfTime').value=`${pad(pred.getHours())}:${pad(pred.getMinutes())}`}
function runWhatIf(){let v=$('whatIfTime').value;if(!v)return;let [h,m]=v.split(':').map(Number),now=new Date(),finish=new Date(now);finish.setHours(h,m,0,0);if(finish<now)finish.setDate(finish.getDate()+1);let c=calc(dayKey(now),true),extra=(finish-now)/60000,projected=Math.round(c.work+c.credit+Math.max(0,extra)-data.settings.targetMinutes),balance=runningBalance()+projected;$('whatIfResult').innerHTML=`<b>Projected day: ${fmt(projected)}</b><br><span style="color:var(--muted)">Estimated running balance: ${fmt(balance)}</span>`}
function setSearchFilter(f,b){searchFilter=f;document.querySelectorAll('.filter-pill').forEach(x=>x.classList.toggle('active',x===b));renderSearch()}
function renderSearch(){let q=($('globalSearch')?.value||'').trim().toLowerCase(),items=[];allDates().sort().reverse().forEach(d=>{let ev=eventsFor(d),sp=special(d),text=[d,sp?.type,...ev.flatMap(e=>[e.type,e.location,e.note])].filter(Boolean).join(' ').toLowerCase();let match=!q||text.includes(q),type=sp?'leave':'work';if(!match)return;if(searchFilter==='leave'&&!sp)return;if(searchFilter==='work'&&sp)return;if(searchFilter==='location'&&!ev.some(e=>e.location&&(!q||e.location.toLowerCase().includes(q))))return;if(searchFilter==='notes'&&!ev.some(e=>e.note&&(!q||e.note.toLowerCase().includes(q))))return;let c=calc(d,false);items.push({d,sp,ev,c})});$('searchResults').innerHTML=items.length?items.slice(0,60).map(x=>`<button class="result-card" style="text-align:left;color:inherit;width:100%" onclick="showDay('${x.d}');goScreen('calendar')"><h4>${new Date(x.d+'T12:00').toLocaleDateString([],{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</h4><p>${x.sp?x.sp.type.replaceAll('_',' '):`${plain(x.c.work)} worked · ${fmt(flexFor(x.d,false))} flexi`}${x.ev.find(e=>e.location)?' · '+escapeHTML(x.ev.find(e=>e.location).location):''}</p></button>`).join(''):'<div class="empty">No matching records found.</div>'}
function renderPlanner(){let allowance=Number(data.settings.annualLeaveHours||0),used=annualLeaveUsed(),remain=Math.max(0,allowance-used),flex=data.days.filter(x=>x.type==='flexi_day').length;$('plannerAllowance').textContent=allowance?allowance.toFixed(1)+'h':'Not set';$('plannerUsed').textContent=used.toFixed(1)+'h';$('plannerRemaining').textContent=allowance?remain.toFixed(1)+'h':'—';$('plannerFlexiDays').textContent=flex;$('plannerYearTitle').textContent=`${plannerYear} year planner`;let advice=[];if(!allowance)advice.push({i:'⚙',t:'Set your allowance',p:'Add your annual leave allowance in Settings to unlock remaining-leave guidance.'});else if(remain>allowance*.6)advice.push({i:'🌴',t:'Plenty of leave available',p:'You still have most of your allowance available to plan.'});else if(remain<allowance*.2)advice.push({i:'!',t:'Leave nearly used',p:'Check future bookings before adding more annual leave.'});else advice.push({i:'✓',t:'Leave looks balanced',p:'Your recorded usage is within a comfortable range.'});advice.push({i:'✨',t:'Flexi-day position',p:`Your current balance is ${fmt(runningBalance())}.`});$('plannerAdvice').innerHTML=advice.map(x=>`<div class="advice"><div class="advice-ico">${x.i}</div><div><b>${x.t}</b><p>${x.p}</p></div></div>`).join('');let html='';for(let m=0;m<12;m++){let first=new Date(plannerYear,m,1),days=new Date(plannerYear,m+1,0).getDate(),offset=(first.getDay()+6)%7,cells='<div class="mini-days">';for(let i=0;i<offset;i++)cells+='<div></div>';for(let d=1;d<=days;d++){let k=`${plannerYear}-${pad(m+1)}-${pad(d)}`,sp=special(k),cls=sp?(sp.type.includes('flexi')?'flexi':'leave'):'';cells+=`<div class="mini-day ${cls}" title="${k}${sp?' · '+sp.type:''}">${d}</div>`}cells+='</div>';html+=`<div class="mini-month"><b>${first.toLocaleDateString([],{month:'short'})}</b>${cells}</div>`}$('yearPlanner').innerHTML=html;$('goalFlexi').value=data.settings.goalFlexiHours||0;$('goalDays').value=data.settings.goalMonthlyDays||0;$('goalFlexiDisplay').textContent=fmt((data.settings.goalFlexiHours||0)*60);$('goalDaysDisplay').textContent=(data.settings.goalMonthlyDays||0)+' days';renderGoalProgress()}
function saveGoals(){data.settings.goalFlexiHours=Number($('goalFlexi').value||0);data.settings.goalMonthlyDays=Number($('goalDays').value||0);persist();toast('Goals saved')}
function saveReminderSettings(){data.settings.remindBreak=$('remindBreak').checked;data.settings.remindFinish=$('remindFinish').checked;data.settings.remindStart=$('remindStart').checked;localStorage.setItem(KEY,JSON.stringify(data));toast('Reminder settings saved')}
function goScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));
function setWorkMode(mode){
  data.settings.workMode=mode;
  let location=mode==='Home Visits'?'Home Visit':mode;
  if(mode==='Hybrid') location=latestLocation()||data.settings.defaultLocation||'Home';
  data.settings.defaultLocation=location;
  localStorage.setItem(KEY,JSON.stringify(data));
  let s=currentState();
  if(s==='idle'||s==='finished') addEvent('work',{location,note:`${mode} day`});
  else if(latestLocation()!==location) addEvent('location',{location,note:`${mode} mode`});
  toast(`${mode} mode selected`);
}
function travelIsActive(){return currentState()==='work_travel'}
function toggleTravel(){
  let s=currentState();
  if(s==='idle'||s==='finished'){
    addEvent('work_travel',{location:'Work travel',note:'Paid travel'});
    data.settings.travelStartedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(data));toast('Paid travel started');return;
  }
  if(s==='work_travel'){
    addEvent('work',{location:latestNonTravelLocation()||data.settings.defaultLocation||'Home Visit',note:'Paid travel ended'});
    data.settings.travelStartedAt=null;localStorage.setItem(KEY,JSON.stringify(data));toast('Paid travel ended');return;
  }
  addEvent('work_travel',{location:latestLocation()||'Work travel',note:'Paid travel'});
  data.settings.travelStartedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(data));toast('Paid travel started');
}
function latestNonTravelLocation(){let ev=eventsFor(dayKey(Date.now())).filter(e=>e.location&&e.type!=='work_travel');return ev.length?ev[ev.length-1].location:''}
function liveFinishInfo(){
  let s=currentState(),d=dayKey(Date.now()),c=calc(d,true),target=Number(data.settings.targetMinutes||480),remaining=Math.max(0,target-c.work-c.credit);
  if(s==='idle')return{time:'—',detail:'Choose a work mode or start work to calculate your finish time.'};
  if(s==='finished')return{time:'Done',detail:`Today finished at ${clock(eventsFor(d).slice(-1)[0].time)} · ${fmt(flexFor(d,false))} flexi.`};
  let predicted=Date.now()+remaining*60000;
  return{time:remaining<=0?'Leave now':clock(predicted),detail:remaining<=0?`You have met today’s target · ${fmt(flexFor(d,true))} flexi so far.`:`${plain(remaining)} remaining · projected ${fmt(flexFor(d,true))} flexi now.`};
}
function renderWorkModeTools(){
  let mode=data.settings.workMode||'',info=liveFinishInfo();
  if($('modeChip'))$('modeChip').textContent=mode||'Not set';
  document.querySelectorAll('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
  if($('liveFinishTime'))$('liveFinishTime').textContent=info.time;
  if($('liveFinishDetail'))$('liveFinishDetail').textContent=info.detail;
  if($('travelButton'))$('travelButton').textContent=travelIsActive()?'✓ End paid travel':'🚗 Start paid travel';
}
function openQuickAdd(){$('quickAddDialog').showModal()}
function quickAddMeeting(){closeDialog('quickAddDialog');quickAction('meeting')}
function quickAddBreak(){closeDialog('quickAddDialog');quickAction('paid_break')}
function quickAddLunch(){closeDialog('quickAddDialog');quickAction('lunch')}
function quickAddNote(){let note=prompt('Add a short note to today’s diary:');if(!note)return;closeDialog('quickAddDialog');data.events.push({id:'e'+Date.now()+Math.random().toString(16).slice(2),type:'note',time:Date.now(),note:note.trim()});persist();toast('Note added')}

document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='calendar')renderCalendar();if(id==='leave')renderLeave();if(id==='settings')renderSettings();if(id==='coachScreen')renderCoach();if(id==='planner')renderPlanner();if(id==='searchScreen')renderSearch();window.scrollTo({top:0,behavior:'smooth'})}
function renderProfessional(){renderCoach();renderPlanner();renderSearch();if($('remindBreak')){$('remindBreak').checked=!!data.settings.remindBreak;$('remindFinish').checked=!!data.settings.remindFinish;$('remindStart').checked=!!data.settings.remindStart}}
function render(){renderTheme();renderToday();renderCalendar();renderReports();renderLeave();renderSettings();renderProfessional()}
function openStart(){$('startLocation').value=data.settings.defaultLocation||'Home';$('startDialog').showModal()}
function confirmStart(){let loc=$('startLocation').value;if(loc==='Other')loc=prompt('Enter location')||'Other';closeDialog('startDialog');addEvent('work',{location:loc});toast('Work started')}
function resumeWork(){addEvent('work',{location:latestLocation()||data.settings.defaultLocation});toast('Work resumed')}
function openPause(){$('pauseDialog').showModal()}function confirmPause(){let note=$('pauseReason').value;if(note==='Other')note=prompt('Reason for pausing')||'Other';closeDialog('pauseDialog');addEvent('pause',{note});toast('Work paused')}
function openLocation(){$('newLocation').value=latestLocation()||'';$('locationDialog').showModal()}function confirmLocation(){let loc=$('newLocation').value.trim();if(!loc)return;closeDialog('locationDialog');addEvent('location',{location:loc});toast('Location updated')}
function finishWork(){if(!confirm('Finish your workday now?'))return;addEvent('finish');toast('Day finished')}
function undoLast(){let ev=eventsFor(dayKey(Date.now()));if(!ev.length)return toast('Nothing to undo');data.events=data.events.filter(e=>e.id!==ev[ev.length-1].id);persist();toast('Last action undone')}
function editEntry(id){creatingEntry=false;let e=data.events.find(x=>x.id===id);if(!e)return;$('editId').value=id;document.querySelector('#editDialog h2').textContent='Edit entry';$('deleteEntryButton').style.display='';$('saveEntryButton').textContent='Save';$('editType').value=e.type;$('editTime').value=new Date(e.time-new Date(e.time).getTimezoneOffset()*60000).toISOString().slice(0,16);$('editLocation').value=e.location||'';$('editNote').value=e.note||'';$('editCredit').value=e.creditMinutes||'';$('editDialog').showModal()}
function saveEdited(){let id=$('editId').value,t=new Date($('editTime').value).getTime();if(!t)return toast('Choose a valid date and time');let e=creatingEntry?null:data.events.find(x=>x.id===id);if(creatingEntry){e={id:'e'+Date.now()+Math.random().toString(16).slice(2)};data.events.push(e)}if(!e)return;e.type=$('editType').value;e.time=t;e.location=$('editLocation').value.trim();e.note=$('editNote').value.trim();e.creditMinutes=Number($('editCredit').value||0);closeDialog('editDialog');localStorage.setItem(KEY,JSON.stringify(data));render();showDay(dayKey(t));toast(creatingEntry?'Entry added':'Entry updated');creatingEntry=false}
function deleteEdited(){let id=$('editId').value;if(!id||!confirm('Delete this entry?'))return;let d=selectedDay;data.events=data.events.filter(e=>e.id!==id);closeDialog('editDialog');localStorage.setItem(KEY,JSON.stringify(data));render();showDay(d);toast('Entry deleted')}
function closeDialog(id){$(id).close()}
function moveMonth(n){monthCursor.setMonth(monthCursor.getMonth()+n);renderCalendar()}
function saveLeave(){let date=$('leaveDate').value,type=$('leaveType').value,hours=Number($('leaveHours').value||0);if(!date)return alert('Choose a date.');data.days=data.days.filter(x=>x.date!==date);data.days.push({date,type,hours});persist();toast('Leave added')}
function deleteLeave(index){let sorted=[...data.days].sort((a,b)=>b.date.localeCompare(a.date)),target=sorted[index];data.days=data.days.filter(x=>x!==target);persist()}
function saveSettings(){data.settings.targetMinutes=Math.round(Number($('targetHours').value||8)*60);data.settings.startingBalance=Number($('startingBalance').value||0);data.settings.paidBreakLimit=Number($('paidBreakLimit').value||0);data.settings.paidBreakCount=Number($('paidBreakCount').value||0);data.settings.usualLunchMinutes=Number($('lunchMinutes').value||30);data.settings.defaultLocation=$('defaultLocation').value.trim()||'Home';data.settings.annualLeaveHours=Number($('annualLeave').value||0);persist();toast('Settings saved')}
function exportCSV(){let rows=[['date','type','worked_minutes','flexi_minutes','timeline']];allDates().forEach(d=>{let sp=special(d),c=calc(d,false);rows.push([d,sp?sp.type:'working_day',Math.round(c.work),flexFor(d,false),eventsFor(d).map(e=>`${clock(e.time)} ${labels[e.type]||e.type}`).join(' | ')])});download('flexi-buddy-report.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function exportBackup(){download('flexi-buddy-backup.json',JSON.stringify(data,null,2),'application/json')}
function restoreBackup(ev){let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.settings||!Array.isArray(d.events))throw 0;if(confirm('Replace current data with this backup?')){data=d;data.settings={...defaults().settings,...data.settings};persist();toast('Backup restored')}}catch(e){alert('That is not a valid Flexi Buddy backup.')}};r.readAsText(f)}
function resetAll(){if(confirm('Erase every Flexi Buddy record and setting? This cannot be undone.')){localStorage.removeItem(KEY);data=defaults();persist()}}
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>goScreen(b.dataset.screen));
$('leaveDate').value=dayKey(Date.now());
render();setInterval(()=>{if(document.getElementById('today').classList.contains('active'))renderToday()},30000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');


// Flexi Buddy 5.5 — favourites and automatic work diary
const favouriteActions={
  wfh:{icon:'🏠',label:'Start WFH',hint:'Home work mode',run:()=>setWorkMode('Home')},
  office:{icon:'🏢',label:'Start office',hint:'Office work mode',run:()=>setWorkMode('Office')},
  visits:{icon:'🚗',label:'Home visits',hint:'Visits work mode',run:()=>setWorkMode('Home Visits')},
  hybrid:{icon:'🔀',label:'Hybrid day',hint:'Mixed locations',run:()=>setWorkMode('Hybrid')},
  quick:{icon:'⚡',label:'Quick work',hint:'Email or messages',run:()=>openQuickWork()},
  travel:{icon:'🛣',label:'Paid travel',hint:'Start or stop',run:()=>toggleTravel()},
  lunch:{icon:'🍽',label:'Lunch',hint:'Start lunch',run:()=>quickAction('lunch')},
  break:{icon:'☕',label:'Paid break',hint:'Start break',run:()=>quickAction('paid_break')},
  meeting:{icon:'👥',label:'Meeting',hint:'Add to timeline',run:()=>quickAction('meeting')},
  note:{icon:'📝',label:'Add note',hint:'Diary note',run:()=>quickAddNote()}
};
function runFavourite(key){let a=favouriteActions[key];if(a)a.run()}
function renderFavourites(){
  if(!$('favouriteGrid'))return;
  let fav=(data.settings.favourites||defaults().settings.favourites).filter(k=>favouriteActions[k]).slice(0,6);
  $('favouriteGrid').innerHTML=fav.map(k=>{let a=favouriteActions[k];return `<button class="favourite-action" onclick="runFavourite('${k}')"><span>${a.icon}</span>${a.label}<small>${a.hint}</small></button>`}).join('');
}
function openFavouriteSettings(){
  let selected=new Set(data.settings.favourites||defaults().settings.favourites);
  $('favouriteSettings').innerHTML=Object.entries(favouriteActions).map(([k,a])=>`<label class="favourite-option"><input type="checkbox" value="${k}" ${selected.has(k)?'checked':''}><span>${a.icon} ${a.label}</span></label>`).join('');
  $('favouriteDialog').showModal();
}
function saveFavouriteSettings(){
  let chosen=[...$('favouriteSettings').querySelectorAll('input:checked')].map(x=>x.value).slice(0,6);
  if(!chosen.length)return alert('Choose at least one favourite.');
  data.settings.favourites=chosen;closeDialog('favouriteDialog');persist();toast('Favourites updated');
}
function eventDiaryLine(e,next){
  let duration=next?Math.max(0,Math.round((next.time-e.time)/60000)):0;
  let at=clock(e.time),loc=e.location?` at ${e.location}`:'';
  if(e.type==='work')return `• Started or resumed work${loc} at ${at}.`;
  if(e.type==='location')return `• Changed work location to ${e.location||'another location'} at ${at}.`;
  if(e.type==='work_travel')return `• Paid work travel started at ${at}${duration?` and lasted ${plain(duration)}`:''}.`;
  if(e.type==='paid_break')return `• Took a paid break at ${at}${duration?` for ${plain(duration)}`:''}.`;
  if(e.type==='lunch')return `• Took lunch at ${at}${duration?` for ${plain(duration)}`:''}.`;
  if(e.type==='pause'||e.type==='unpaid_break')return `• Work paused at ${at}${duration?` for ${plain(duration)}`:''}${e.note?` (${e.note})`:''}.`;
  if(e.type==='quick_work')return `• ${e.note||'Quick work'} — ${plain(Number(e.creditMinutes||0))}.`;
  if(e.type==='credit')return `• Added ${plain(Number(e.creditMinutes||0))} work credit${e.note?` for ${e.note}`:''}.`;
  if(e.type==='note')return `• ${e.note||'Note added'}.`;
  if(e.type==='finish')return `• Finished work at ${at}.`;
  return e.note?`• ${e.note}.`:'';
}
function generatedDiary(d=dayKey(Date.now())){
  let ev=eventsFor(d),sp=special(d),dateLabel=new Date(d+'T12:00').toLocaleDateString([],{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  if(sp)return `${dateLabel}\n\n${({annual_leave:'Annual leave',flexi_day:'Flexi day',part_flexi:'Part flexi leave',sick:'Sick leave',dependants:'Dependants leave',special:'Special leave',part_year:'Part-year day',bank_holiday:'Bank holiday'}[sp.type]||'Leave')} recorded${sp.hours?` (${sp.hours} hours)`:''}.`;
  if(!ev.length)return `${dateLabel}\n\nNo work activity has been recorded yet.`;
  let c=calc(d,d===dayKey(Date.now())&&!hasFinished(d)),lines=ev.map((e,i)=>eventDiaryLine(e,ev[i+1])).filter(Boolean),flex=flexFor(d,d===dayKey(Date.now())&&!hasFinished(d));
  let status=hasFinished(d)?`Worked ${plain(c.work+c.credit)} in total and finished with ${fmt(flex)} flexi.`:`So far, ${plain(c.work+c.credit)} has been recorded with ${fmt(flex)} projected flexi.`;
  return `${dateLabel}\n\n${lines.join('\n')}\n\n${status}`;
}
function currentDiary(){let d=dayKey(Date.now());return (data.settings.diaryEdits||{})[d]||generatedDiary(d)}
function renderDiary(){if(!$('diaryText'))return;let text=currentDiary();$('diaryText').textContent=text;$('diaryText').classList.toggle('diary-empty',eventsFor(dayKey(Date.now())).length===0)}
function editDiary(){$('diaryEditor').value=currentDiary();$('diaryDialog').showModal()}
function saveDiaryEdit(){let d=dayKey(Date.now());data.settings.diaryEdits=data.settings.diaryEdits||{};data.settings.diaryEdits[d]=$('diaryEditor').value.trim();closeDialog('diaryDialog');persist();toast('Diary wording saved')}
async function copyDiary(){try{await navigator.clipboard.writeText(currentDiary());toast('Diary copied')}catch(e){let t=document.createElement('textarea');t.value=currentDiary();document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('Diary copied')}}
function downloadDiary(){let d=dayKey(Date.now());download(`flexi-buddy-diary-${d}.txt`,currentDiary(),'text/plain')}
